// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    reciters,
    appSettings,
    surahs,
    recordingEditions,
    audioAssets,
    savedPassages,
    passageInsertBounds,
    passageUpdateBounds,
    assetIdentityImmutable,
    favorites,
    favoriteInsertTarget,
    favoriteUpdateTarget,
    passageDeleteFavorite,
    surahDeleteFavorite,
    downloads,
    downloadInsertVerified,
    downloadUpdateVerified,
    playbackCheckpoints,
    checkpointInsertBounds,
    checkpointUpdateBounds,
    listeningSessions,
    dailyActivity,
    activityEvents,
  ];
  late final Shape0 reciters = Shape0(
    source: i0.VersionedTable(
      entityName: 'reciters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 appSettings = Shape1(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 surahs = Shape2(
    source: i0.VersionedTable(
      entityName: 'surahs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_13, _column_14, _column_15, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 recordingEditions = Shape3(
    source: i0.VersionedTable(
      entityName: 'recording_editions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_17, _column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 audioAssets = Shape4(
    source: i0.VersionedTable(
      entityName: 'audio_assets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(availability <> \'published\' OR(duration_ms IS NOT NULL AND byte_size IS NOT NULL AND sha256 IS NOT NULL))',
        'UNIQUE(edition_id, surah_number, version)',
      ],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 savedPassages = Shape5(
    source: i0.VersionedTable(
      entityName: 'saved_passages',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((repeat_mode = \'finite\' AND play_count IS NOT NULL AND play_count BETWEEN 1 AND 999)OR(repeat_mode = \'continuous\' AND play_count IS NULL))',
      ],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger passageInsertBounds = i1.Trigger(
    'CREATE TRIGGER passage_insert_bounds BEFORE INSERT ON saved_passages BEGIN SELECT RAISE (ABORT, \'Passage requires verified duration and valid bounds\') WHERE NOT EXISTS (SELECT 1 FROM audio_assets WHERE id = NEW.asset_id AND duration_ms IS NOT NULL AND NEW.end_ms <= duration_ms);END',
    'passage_insert_bounds',
  );
  final i1.Trigger passageUpdateBounds = i1.Trigger(
    'CREATE TRIGGER passage_update_bounds BEFORE UPDATE ON saved_passages BEGIN SELECT RAISE (ABORT, \'Passage requires verified duration and valid bounds\') WHERE NOT EXISTS (SELECT 1 FROM audio_assets WHERE id = NEW.asset_id AND duration_ms IS NOT NULL AND NEW.end_ms <= duration_ms);END',
    'passage_update_bounds',
  );
  final i1.Trigger assetIdentityImmutable = i1.Trigger(
    'CREATE TRIGGER asset_identity_immutable BEFORE UPDATE ON audio_assets BEGIN SELECT RAISE (ABORT, \'Recording bytes and identity are immutable\') WHERE OLD.id <> NEW.id OR OLD.edition_id <> NEW.edition_id OR OLD.surah_number <> NEW.surah_number OR OLD.version <> NEW.version OR(OLD.sha256 IS NOT NULL AND(NEW.sha256 IS NOT OLD.sha256 OR NEW.byte_size IS NOT OLD.byte_size OR NEW.duration_ms IS NOT OLD.duration_ms OR NEW.url IS NOT OLD.url));END',
    'asset_identity_immutable',
  );
  late final Shape6 favorites = Shape6(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(type, target_id)'],
      columns: [_column_40, _column_41, _column_38],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger favoriteInsertTarget = i1.Trigger(
    'CREATE TRIGGER favorite_insert_target BEFORE INSERT ON favorites BEGIN SELECT RAISE (ABORT, \'Unknown favorite target\') WHERE(NEW.type = \'surah\' AND NOT EXISTS (SELECT 1 FROM surahs WHERE CAST(number AS TEXT) = NEW.target_id))OR(NEW.type = \'passage\' AND NOT EXISTS (SELECT 1 FROM saved_passages WHERE id = NEW.target_id));END',
    'favorite_insert_target',
  );
  final i1.Trigger favoriteUpdateTarget = i1.Trigger(
    'CREATE TRIGGER favorite_update_target BEFORE UPDATE ON favorites BEGIN SELECT RAISE (ABORT, \'Favorite target is immutable\') WHERE NEW.type <> OLD.type OR NEW.target_id <> OLD.target_id;END',
    'favorite_update_target',
  );
  final i1.Trigger passageDeleteFavorite = i1.Trigger(
    'CREATE TRIGGER passage_delete_favorite AFTER DELETE ON saved_passages BEGIN DELETE FROM favorites WHERE type = \'passage\' AND target_id = OLD.id;END',
    'passage_delete_favorite',
  );
  final i1.Trigger surahDeleteFavorite = i1.Trigger(
    'CREATE TRIGGER surah_delete_favorite AFTER DELETE ON surahs BEGIN DELETE FROM favorites WHERE type = \'surah\' AND target_id = CAST(OLD.number AS TEXT);END',
    'surah_delete_favorite',
  );
  late final Shape7 downloads = Shape7(
    source: i0.VersionedTable(
      entityName: 'downloads',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(state <> \'verified\' OR(relative_path IS NOT NULL AND verified_sha256 IS NOT NULL))',
      ],
      columns: [
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger downloadInsertVerified = i1.Trigger(
    'CREATE TRIGGER download_insert_verified BEFORE INSERT ON downloads BEGIN SELECT RAISE (ABORT, \'Download integrity mismatch\') WHERE NEW.state = \'verified\' AND NOT EXISTS (SELECT 1 FROM audio_assets WHERE id = NEW.asset_id AND byte_size = NEW.received_bytes AND sha256 = NEW.verified_sha256);END',
    'download_insert_verified',
  );
  final i1.Trigger downloadUpdateVerified = i1.Trigger(
    'CREATE TRIGGER download_update_verified BEFORE UPDATE ON downloads BEGIN SELECT RAISE (ABORT, \'Download integrity mismatch\') WHERE NEW.state = \'verified\' AND NOT EXISTS (SELECT 1 FROM audio_assets WHERE id = NEW.asset_id AND byte_size = NEW.received_bytes AND sha256 = NEW.verified_sha256);END',
    'download_update_verified',
  );
  late final Shape8 playbackCheckpoints = Shape8(
    source: i0.VersionedTable(
      entityName: 'playback_checkpoints',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_49,
        _column_50,
        _column_29,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger checkpointInsertBounds = i1.Trigger(
    'CREATE TRIGGER checkpoint_insert_bounds BEFORE INSERT ON playback_checkpoints BEGIN SELECT RAISE (ABORT, \'Invalid checkpoint asset/position\') WHERE NOT EXISTS (SELECT 1 FROM audio_assets WHERE id = NEW.asset_id AND duration_ms IS NOT NULL AND NEW.source_position_ms <= duration_ms);SELECT RAISE (ABORT, \'Checkpoint passage asset mismatch\') WHERE NEW.passage_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM saved_passages WHERE id = NEW.passage_id AND asset_id = NEW.asset_id);END',
    'checkpoint_insert_bounds',
  );
  final i1.Trigger checkpointUpdateBounds = i1.Trigger(
    'CREATE TRIGGER checkpoint_update_bounds BEFORE UPDATE ON playback_checkpoints BEGIN SELECT RAISE (ABORT, \'Invalid checkpoint asset/position\') WHERE NOT EXISTS (SELECT 1 FROM audio_assets WHERE id = NEW.asset_id AND duration_ms IS NOT NULL AND NEW.source_position_ms <= duration_ms);SELECT RAISE (ABORT, \'Checkpoint passage asset mismatch\') WHERE NEW.passage_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM saved_passages WHERE id = NEW.passage_id AND asset_id = NEW.asset_id);END',
    'checkpoint_update_bounds',
  );
  late final Shape9 listeningSessions = Shape9(
    source: i0.VersionedTable(
      entityName: 'listening_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_51,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 dailyActivity = Shape10(
    source: i0.VersionedTable(
      entityName: 'daily_activity',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_61, _column_62, _column_58, _column_63, _column_64],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 activityEvents = Shape11(
    source: i0.VersionedTable(
      entityName: 'activity_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_65, _column_66, _column_67, _column_68],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get arabicName =>
      columnsByName['arabic_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get attribution =>
      columnsByName['attribution']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceInfo =>
      columnsByName['source_info']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(trim(display_name)) > 0)',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'arabic_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'attribution',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_info',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get theme =>
      columnsByName['theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get reducedMotion =>
      columnsByName['reduced_motion']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get networkPolicy =>
      columnsByName['network_policy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultReciterId =>
      columnsByName['default_reciter_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get dailyGoalMs =>
      columnsByName['daily_goal_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get preferencesVersion =>
      columnsByName['preferences_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedUtcMs =>
      columnsByName['updated_utc_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY CHECK (id = 1)',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'system\' CHECK (theme IN (\'system\', \'light\', \'dark\'))',
      defaultValue: const i1.CustomExpression('\'system\''),
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reduced_motion',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (reduced_motion IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_8(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'network_policy',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL DEFAULT \'wifi\' CHECK (network_policy IN (\'wifi\', \'any\'))',
  defaultValue: const i1.CustomExpression('\'wifi\''),
);
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_reciter_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES reciters(id)',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'daily_goal_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 300000 CHECK (daily_goal_ms >= 0)',
      defaultValue: const i1.CustomExpression('300000'),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'preferences_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (preferences_version > 0)',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get number =>
      columnsByName['number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get arabicName =>
      columnsByName['arabic_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get transliteration =>
      columnsByName['transliteration']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get searchAliases =>
      columnsByName['search_aliases']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL PRIMARY KEY CHECK (number BETWEEN 1 AND 114)',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'arabic_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(trim(arabic_name)) > 0)',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'transliteration',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(trim(transliteration)) > 0)',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'search_aliases',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (json_valid(search_aliases))',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reciterId =>
      columnsByName['reciter_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get riwayah =>
      columnsByName['riwayah']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceNotes =>
      columnsByName['source_notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reciter_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES reciters(id)',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'riwayah',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_notes',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get editionId =>
      columnsByName['edition_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get surahNumber =>
      columnsByName['surah_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mimeType =>
      columnsByName['mime_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get byteSize =>
      columnsByName['byte_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get availability =>
      columnsByName['availability']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'edition_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES recording_editions(id)',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'surah_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES surahs(number)',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (version > 0)',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (url LIKE \'https://%\')',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (duration_ms > 0)',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_size',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (byte_size > 0)',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sha256',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK (length(sha256) = 64 AND sha256 NOT GLOB \'*[^0-9a-f]*\')',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'availability',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (availability IN (\'unavailable\', \'published\', \'retired\'))',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assetId =>
      columnsByName['asset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startMs =>
      columnsByName['start_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endMs =>
      columnsByName['end_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get repeatMode =>
      columnsByName['repeat_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get playCount =>
      columnsByName['play_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get gapMs =>
      columnsByName['gap_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get speed =>
      columnsByName['speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdUtcMs =>
      columnsByName['created_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedUtcMs =>
      columnsByName['updated_utc_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'asset_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES audio_assets(id)',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(trim(title)) > 0)',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (start_ms >= 0)',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (end_ms - start_ms >= 1000)',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'repeat_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (repeat_mode IN (\'finite\', \'continuous\'))',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'play_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'gap_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (gap_ms IN (0, 2000, 5000, 10000))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<double> _column_36(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'speed',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints:
          'NOT NULL DEFAULT 1.0 CHECK (speed BETWEEN 0.5 AND 2.0)',
      defaultValue: const i1.CustomExpression('1.0'),
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (updated_utc_ms >= created_utc_ms)',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get targetId =>
      columnsByName['target_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdUtcMs =>
      columnsByName['created_utc_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (type IN (\'surah\', \'passage\'))',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get assetId =>
      columnsByName['asset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nativeTaskId =>
      columnsByName['native_task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get receivedBytes =>
      columnsByName['received_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get verifiedSha256 =>
      columnsByName['verified_sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedUtcMs =>
      columnsByName['updated_utc_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'asset_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY REFERENCES audio_assets(id)',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (relative_path <> \'\' AND relative_path NOT LIKE \'/%\' AND relative_path NOT LIKE \'%..%\' AND relative_path NOT LIKE \'%:%\' AND relative_path NOT LIKE \'%\\%\')',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'native_task_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (state IN (\'queued\', \'running\', \'verifying\', \'verified\', \'failed\', \'cancelled\'))',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'received_bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (received_bytes >= 0)',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'verified_sha256',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assetId =>
      columnsByName['asset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get passageId =>
      columnsByName['passage_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get currentPass =>
      columnsByName['current_pass']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get remainingCount =>
      columnsByName['remaining_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sourcePositionMs =>
      columnsByName['source_position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get settingsSnapshot =>
      columnsByName['settings_snapshot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedUtcMs =>
      columnsByName['updated_utc_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scope',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (scope IN (\'full\', \'passage\'))',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'passage_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES saved_passages(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'current_pass',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (current_pass > 0)',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remaining_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (remaining_count >= 0)',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (source_position_ms >= 0)',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'settings_snapshot',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (json_valid(settings_snapshot))',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get assetId =>
      columnsByName['asset_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get passageId =>
      columnsByName['passage_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedUtcMs =>
      columnsByName['started_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedUtcMs =>
      columnsByName['ended_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playedWallMs =>
      columnsByName['played_wall_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get speed =>
      columnsByName['speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get completionReason =>
      columnsByName['completion_reason']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (ended_utc_ms >= started_utc_ms)',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'played_wall_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (played_wall_ms >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<double> _column_59(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'speed',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL CHECK (speed BETWEEN 0.5 AND 2.0)',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completion_reason',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get localDate =>
      columnsByName['local_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timezonePolicy =>
      columnsByName['timezone_policy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get playedWallMs =>
      columnsByName['played_wall_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get goalMs =>
      columnsByName['goal_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get qualified =>
      columnsByName['qualified']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL PRIMARY KEY CHECK (length(local_date) = 10)',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'timezone_policy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'goal_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (goal_ms >= 0)',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'qualified',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (qualified IN (0, 1))',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDate =>
      columnsByName['local_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get playedWallMs =>
      columnsByName['played_wall_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get utcMs =>
      columnsByName['utc_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES listening_sessions(id)',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES daily_activity(local_date)',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'played_wall_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (played_wall_ms > 0)',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'utc_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
